HappyScaff/Models/Makaleler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyScaff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makaleler
    {
        public int MakaleId { get; set; }
        public string MakaleBaslik { get; set; }
        public string MakaleIcerik { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}

HappyScaff/Controllers/MakalelerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HappyScaff.Models;

namespace HappyScaff.Controllers
{
    public class MakalelerController : Controller
    {
        private HappyScafEntities db = new HappyScafEntities();

        // GET: Makaleler/MakalelerIndex
        public ActionResult MakalelerIndex()
        {
            var makaleler = db.Makaleler.Include(m => m.Kategoriler);
            return View(makaleler.ToList());
        }

        /*
        // GET: Makaleler/MakalelerDetails/5
        public ActionResult MakalelerDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makaleler makaleler = db.Makaleler.Find(id);
            if (makaleler == null)
            {
                return HttpNotFound();
            }
            return View(makaleler);
        }
        */

        // GET: Makaleler/MakalelerCreate
        public ActionResult MakalelerCreate()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoriler, "KategoriId", "KategoriBaslik");
            return View();
        }

        // POST: Makaleler/MakalelerCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MakalelerCreate([Bind(Include = "MakaleId,MakaleBaslik,MakaleIcerik,KategoriId,Kategoriler")] Makaleler makaleler)
        {
            if (ModelState.IsValid)
            {
                db.Makaleler.Add(makaleler);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Makaleler record");
                return RedirectToAction("MakalelerIndex");
            }

            ViewBag.KategoriId = new SelectList(db.Kategoriler, "KategoriId", "KategoriBaslik", makaleler.KategoriId);
            DisplayErrorMessage();
            return View(makaleler);
        }

        // GET: Makaleler/MakalelerEdit/5
        public ActionResult MakalelerEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makaleler makaleler = db.Makaleler.Find(id);
            if (makaleler == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(db.Kategoriler, "KategoriId", "KategoriBaslik", makaleler.KategoriId);
            return View(makaleler);
        }

        // POST: MakalelerMakaleler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MakalelerEdit([Bind(Include = "MakaleId,MakaleBaslik,MakaleIcerik,KategoriId,Kategoriler")] Makaleler makaleler, int Id)
        {
            if (ModelState.IsValid)
            {
                makaleler.MakaleId = Id;
                db.Entry(makaleler).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Makaleler record");
                return RedirectToAction("MakalelerIndex");
            }
            ViewBag.KategoriId = new SelectList(db.Kategoriler, "KategoriId", "KategoriBaslik", makaleler.KategoriId);
            DisplayErrorMessage();
            return View(makaleler);
        }

        // GET: Makaleler/MakalelerDelete/5
        public ActionResult MakalelerDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Makaleler makaleler = db.Makaleler.Find(id);
            if (makaleler == null)
            {
                return HttpNotFound();
            }
            return View(makaleler);
        }

        // POST: Makaleler/MakalelerDelete/5
        [HttpPost, ActionName("MakalelerDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult MakalelerDeleteConfirmed(int id)
        {
            Makaleler makaleler = db.Makaleler.Find(id);
            db.Makaleler.Remove(makaleler);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Makaleler record");
            return RedirectToAction("MakalelerIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HappyScaff/Views/Makaleler/MakalelerCreate.cshtml
@model HappyScaff.Models.Makaleler

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makaleler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("MakalelerEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MakalelerIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyScaff/Views/Makaleler/MakalelerEdit.cshtml
@model HappyScaff.Models.Makaleler

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makaleler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("MakalelerEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MakalelerIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MakalelerDelete", "Makaleler", new { id=Model.MakaleId}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyScaff/Views/Makaleler/MakalelerEditForm.cshtml
@model HappyScaff.Models.Makaleler

        <div class="form-group">
            @Html.LabelFor(model => model.MakaleBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MakaleBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MakaleBaslik,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MakaleIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MakaleIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MakaleIcerik,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriId,"" , new { @class = "text-danger" })
            </div>
        </div>

HappyScaff/Views/Makaleler/MakalelerIndex.cshtml
@model IEnumerable<HappyScaff.Models.Makaleler>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1){text-align: right;}
    td:nth-child(4){text-align: right;}
</style>
<h2>Index</h2>
<h4>Makaleler</h4>
<p>
    @Html.ActionLink("Create New", "MakalelerCreate")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.MakaleBaslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MakaleIcerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kategoriler.KategoriBaslik)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "MakalelerEdit", new { id=item.MakaleId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MakaleBaslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MakaleIcerik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategoriler.KategoriBaslik)
        </td>

    </tr>
}

</table>