HappyScaff/Models/Kategoriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyScaff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Makaleler = new HashSet<Makaleler>();
        }
    
        public int KategoriId { get; set; }
        public string KategoriBaslik { get; set; }
        public string KategoriIcerik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makaleler> Makaleler { get; set; }
    }
}

HappyScaff/Controllers/KategorilerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HappyScaff.Models;

namespace HappyScaff.Controllers
{
    public class KategorilerController : Controller
    {
        private HappyScafEntities db = new HappyScafEntities();

        // GET: Kategoriler/KategorilerIndex
        public ActionResult KategorilerIndex()
        {
            return View(db.Kategoriler.ToList());
        }

        /*
        // GET: Kategoriler/KategorilerDetails/5
        public ActionResult KategorilerDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }
        */

        // GET: Kategoriler/KategorilerCreate
        public ActionResult KategorilerCreate()
        {
            return View();
        }

        // POST: Kategoriler/KategorilerCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KategorilerCreate([Bind(Include = "KategoriId,KategoriBaslik,KategoriIcerik,Makaleler")] Kategoriler kategoriler)
        {
            if (ModelState.IsValid)
            {

                db.Kategoriler.Add(kategoriler);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a Kategoriler record");
                return RedirectToAction("KategorilerIndex");
            }

            DisplayErrorMessage();
            return View(kategoriler);
        }

        // GET: Kategoriler/KategorilerEdit/5
        public ActionResult KategorilerEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }

        // POST: KategorilerKategoriler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KategorilerEdit([Bind(Include = "KategoriId,KategoriBaslik,KategoriIcerik,Makaleler")] Kategoriler kategoriler, int Id)
        {
            if (ModelState.IsValid)
            {
                kategoriler.KategoriId = Id;
                db.Entry(kategoriler).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a Kategoriler record");
                return RedirectToAction("KategorilerIndex");
            }
            DisplayErrorMessage();
            return View(kategoriler);
        }

        // GET: Kategoriler/KategorilerDelete/5
        public ActionResult KategorilerDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            if (kategoriler == null)
            {
                return HttpNotFound();
            }
            return View(kategoriler);
        }

        // POST: Kategoriler/KategorilerDelete/5
        [HttpPost, ActionName("KategorilerDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult KategorilerDeleteConfirmed(int id)
        {
            Kategoriler kategoriler = db.Kategoriler.Find(id);
            db.Kategoriler.Remove(kategoriler);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a Kategoriler record");
            return RedirectToAction("KategorilerIndex");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HappyScaff/Views/Kategoriler/KategorilerCreate.cshtml
@model HappyScaff.Models.Kategoriler

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategoriler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("KategorilerEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "KategorilerIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyScaff/Views/Kategoriler/KategorilerEdit.cshtml
@model HappyScaff.Models.Kategoriler

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategoriler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("KategorilerEditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "KategorilerIndex")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("KategorilerDelete", "Kategoriler", new { id=Model.KategoriId}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyScaff/Views/Kategoriler/KategorilerEditForm.cshtml
@model HappyScaff.Models.Kategoriler

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriBaslik,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KategoriIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KategoriIcerik,"" , new { @class = "text-danger" })
            </div>
        </div>

HappyScaff/Views/Kategoriler/KategorilerIndex.cshtml
@model IEnumerable<HappyScaff.Models.Kategoriler>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    /*設定 數字靠右*/
    td:nth-child(1){text-align: right;}
</style>
<h2>Index</h2>
<h4>Kategoriler</h4>
<p>
    @Html.ActionLink("Create New", "KategorilerCreate")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.KategoriBaslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KategoriIcerik)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "KategorilerEdit", new { id=item.KategoriId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KategoriBaslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KategoriIcerik)
        </td>

    </tr>
}

</table>